# **By : KHIRANIA Aya**

# **Import libraries**

In [ ]:
import pandas as pd
from google.colab import files
import numpy as np
from datetime import datetime

import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

# **Import dataset**

In [ ]:
uploaded = files.upload()

Saving base de données.xlsx to base de données.xlsx

In [ ]:
# XLSX file
file_path = "base de données.xlsx"

# Read the Excel file, specifying the sheet name or index
df = pd.read_excel(file_path, sheet_name="Sheet1", header=[0, 1])

In [ ]:
# Load the dataset
df

   Unnamed: 0_level_0 Informations personnelles                \
                 code                       Age Sexe indigène
0                   1                2010-01-19    F      NaN
1                   2                2004-11-19    M      NaN
2                   3                2008-01-09    M      NaN
3                   4                2008-11-22    M      NaN
4                   5                2007-01-24    M      NaN
5                   6                2008-08-15    M      NaN
6                   7                2008-06-08    M      NaN
7                   8                2005-11-15    F      NaN
8                   9                2008-12-09    M      NaN
9                  10                2009-07-16    M      NaN
10                 11                2007-05-18    M      NaN
11                 12                2005-01-05    M      NaN
12                 13                2005-08-01    M      NaN
13                 14                2007-03-18    M      NaN
14                 15                2010-01-22    F      NaN
15                 16                2009-03-24    F      NaN
16                 17                2007-12-05    M      NaN
17                 18                2008-01-21    M      NaN
18                 19                2007-07-26    F      NaN
19                 20                2007-11-23    M      NaN
20                 21                2008-12-30    F      NaN
21                 22                2008-04-21    F      NaN
22                 23                2008-11-10    M      NaN
23                 24                2007-05-22    F      NaN
24                 25                2008-09-27    M      NaN
25                 26                2006-03-12    M      NaN
26                 27                2005-11-18    M      NaN
27                 28                2007-02-16    M      NaN
28                 29                2005-11-29    M      NaN
29                 30                2004-09-22    M      NaN
30                 31                2006-04-29    M      NaN
31                 32                2004-11-02    M      NaN
32                 33                2007-03-18    M      NaN
33                 34                2008-03-20    M      NaN
34                 35                2006-10-17    F      NaN
35                 36                2006-09-06    F      NaN
36                 37                2005-06-23    M      NaN
37                 38                2005-07-25    F      NaN
38                 39                2007-05-02    M      NaN
39                 40                2006-01-17    M      NaN

                                                                  \
   problèmes de santé le travail à la maison préscolaire Travail
0           psychique                    oui         non     non
1                 Non                    non         non     non
2                 Non                    non         non     non
3                 Non                    non         non     non
4                 Non                    non         non     non
5                 Non                    non         non     non
6                 Non                    non         non     non
7                 Oui                    oui         non     non
8                 Non                    Non         non     non
9                 Non                    Non         non     non
10                Non                    Non         non     non
11                Non                    Non         non     non
12                Non                    Non         non     non
13                Non                    Non         non     non
14                Non                    Non         non     non
15                Non                    Oui         non     non
16                Non                    Non         non     non
17                Non                    Non         non     non
18                Non                    Non         non     non
19                Non                    Non         non     non
20                Non                    Oui         non     non
21                Non                    Non         non     non
22                Non                    Non         non     non
23                Non                    Oui         non     non
24                Non                    Non         non     non
25                Non                    Non         non     non
26                Non                    Non         non     non
27                Non                    Non         non     non
28                Non                    Non         non     non
29                Non                    Non         non     non
30                Non                    Non         non     non
31                Non                    Non         non     non
32                Non                    Non         non     non
33                Non                    Non         non     non
34                Non                    Non         non     non
35                Non                    Non         non     non
36                Non                    Non         non     non
37                Non                    Non         non     non
38                Non                    Non         non     non
39                Non                    Non         non     non

                        Information familiale  ...  \
   interne / externe Qualification de la mère  ...
0           interne                       non  ...
1            externe                      non  ...
2            externe                      non  ...
3            externe                      non  ...
4            externe                      non  ...
5            externe                      non  ...
6            externe                      non  ...
7            externe                      non  ...
8            Interne                      non  ...
9            externe                      non  ...
10           externe                      non  ...
11           externe                      non  ...
12           externe                      non  ...
13           externe                      non  ...
14           Externe                      non  ...
15           Externe                      non  ...
16           Externe                      non  ...
17           Externe                      non  ...
18           Interne                      non  ...
19           Externe                      non  ...
20           Externe                      non  ...
21           Externe                      non  ...
22           Interne                      non  ...
23           Extrene                      non  ...
24           Extrene                      non  ...
25           Extrene                      non  ...
26           Extrene                      non  ...
27           Extrene                      non  ...
28           Interne                      non  ...
29           Externe                      non  ...
30           Externe                      non  ...
31           Externe                      non  ...
32           Externe                      non  ...
33           Externe                      non  ...
34           Externe                      non  ...
35           Externe                      non  ...
36           Externe                      non  ...
37           Externe                      non  ...
38           Externe                      non  ...
39           Externe                      non  ...

   Informations sur l'école et le lieu de résidence                   \
                                        Electricité  Eau   pc Livres
0                                               oui  oui  non    oui
1                                               oui  oui  non    oui
2                                               oui  oui  non    oui
3                                               oui  oui  non    oui
4                                               oui  oui  non    oui
5                                               oui  oui  non    oui
6                                               oui  oui  non    oui
7                                               oui  oui  non    oui
8                                               oui  oui  non    oui
9                                               oui  oui  non    oui
10                                              oui  oui  non    oui
11                                              oui  oui  non    oui
12                                              oui  oui  non    oui
13                                              oui  oui  non    oui
14                                              oui  oui  non    oui
15                                              oui  oui  non    oui
16                                              oui  oui  non    oui
17                                              oui  oui  non    oui
18                                              oui  oui  non    oui
19                                              oui  oui  non    oui
20                                              oui  oui  non    oui
21                                              oui  oui  non    oui
22                                              oui  oui  non    oui
23                                              oui  oui  non    oui
24                                              oui  oui  non    oui
25                                              oui  oui  non    oui
26                                              oui  oui  non    oui
27                                              oui  oui  non    oui
28                                              oui  oui  non    oui
29                                              oui  oui  non    oui
30                                              oui  oui  non    oui
31                                              oui  oui  non    oui
32                                              oui  oui  non    oui
33                                              oui  oui  non    oui
34                                              oui  oui  non    oui
35                                              oui  oui  non    oui
36                                              oui  oui  non    oui
37                                              oui  oui  non    oui
38                                              oui  oui  non    oui
39                                              oui  oui  non    oui

   Informations démographiques         Informations psychologiques  \
                    État civil Origine                  motivation
0                  célibataire     NaN                         oui
1                  célibataire     NaN                         Non
2                  célibataire     NaN                         Non
3                  célibataire     NaN                         Non
4                  célibataire     NaN                         Non
5                  célibataire     NaN                         Non
6                  célibataire     NaN                         Non
7                  célibataire     NaN                         Oui
8                  célibataire     NaN                         Non
9                  célibataire     NaN                         Non
10                 célibataire     NaN                         Non
11                 célibataire     NaN                         Oui
12                 célibataire     NaN                         Non
13                 célibataire     NaN                         Non
14                 célibataire     NaN                         Oui
15                 célibataire     NaN                         Non
16                 célibataire     NaN                         Non
17                 célibataire     NaN                         Non
18                 célibataire     NaN                         Non
19                 célibataire     NaN                         Non
20                 célibataire     NaN                         Non
21                 célibataire     NaN                         Non
22                 célibataire     NaN                         Non
23                 célibataire     NaN                         Non
24                 célibataire     NaN                         Non
25                 célibataire     NaN                         Non
26                 célibataire     NaN                         Non
27                 célibataire     NaN                         Non
28                 célibataire     NaN                         Non
29                 célibataire     NaN                         Non
30                 célibataire     NaN                         Non
31                 célibataire     NaN                         Non
32                 célibataire     NaN                         Non
33                 célibataire     NaN                         Non
34                 célibataire     NaN                         Non
35                 célibataire     NaN                         Non
36                 célibataire     NaN                         Non
37                 célibataire     NaN                         Non
38                 célibataire     NaN                         Non
39                 célibataire     NaN                         Non

                                               انقطع | مثعثر دراسيا|جيد|
   Style d'apprentissage Satisfaction du cours انقطع | مثعثر دراسيا|جيد|
0                 Normal                   NaN                    انقطعت
1                 Normal                   NaN                     انقطع
2                 Normal                   NaN                     انقطع
3                 Normal                   NaN                     انقطع
4                 Normal                   NaN                     انقطع
5                 Normal                   NaN                     انقطع
6                 Normal                   NaN                     متعثر
7                 Normal                   NaN                    انقطعت
8                 Normal                   NaN                     متعثر
9                 Normal                   NaN                     متعثر
10                Normal                   NaN                     متعثر
11                Normal                   NaN                     متعثر
12                Normal                   NaN                     متعثر
13                Normal                   NaN                     متعثر
14                Normal                   NaN                     متعثر
15                Normal                   NaN                     متعثر
16                Normal                   NaN                     متعثر
17                Normal                   NaN                     متعثر
18                Normal                   NaN                     متعثر
19                Normal                   NaN                     متعثر
20                Normal                   NaN                     متعثر
21                Normal                   NaN                     متعثر
22                Normal                   NaN                     متعثر
23                Normal                   NaN                     متعثر
24                Normal                   NaN                     متعثر
25                Normal                   NaN                     متعثر
26                Normal                   NaN                     متعثر
27                Normal                   NaN                     متعثر
28                Normal                   NaN                     متعثر
29                Normal                   NaN                     متعثر
30                Normal                   NaN                     متعثر
31                Normal                   NaN                     متعثر
32                Normal                   NaN                     متعثر
33                Normal                   NaN                     متعثر
34                Normal                   NaN                     متعثر
35                Normal                   NaN                     متعثر
36                Normal                   NaN                     متعثر
37                Normal                   NaN                     متعثر
38                Normal                   NaN                     متعثر
39                Normal                   NaN                     متعثر

[40 rows x 38 columns]

# **Data Exploration:**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 38 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   (Unnamed: 0_level_0, code)                                                40 non-null     int64
 1   (Informations personnelles, Age)                                          40 non-null     datetime64[ns]
 2   (Informations personnelles, Sexe)                                         40 non-null     object
 3   (Informations personnelles, indigène)                                     0 non-null      float64
 4   (Informations personnelles, problèmes de santé)                           40 non-null     object
 5   (Informations personnelles, le travail à la maison)                       40 non-null     object
 6   (Informations personnelles, préscolaire)                                  40 non-null     object
 7   (Informations personnelles, Travail)                                      40 non-null     object
 8   (Informations personnelles, interne / externe)                            40 non-null     object
 9   (Information familiale, Qualification de la mère)                         40 non-null     object
 10  (Information familiale,  Qualification Du père)                           40 non-null     object
 11  (Information familiale, Profession de la mère)                            40 non-null     object
 12  (Information familiale, Profession du père)                               40 non-null     object
 13  (Information familiale, Divorcé)                                          39 non-null     object
 14  (Information familiale, Mort)                                             40 non-null     object
 15  (Information familiale, Revenu familial)                                  0 non-null      float64
 16  (Information familiale, aide aux devoirs)                                 40 non-null     object
 17  (Performance académique, Specialté)                                       40 non-null     object
 18  (Performance académique, Nombre de répitition)                            40 non-null     int64
 19  (Performance académique, Score primaire)                                  40 non-null     float64
 20  (Performance académique, Score collégial)                                 40 non-null     float64
 21  (Performance académique, Score actuel)                                    40 non-null     float64
 22  (Performance académique, score en mathématiques)                          40 non-null     float64
 23  (Performance académique,  score en langue arabe)                          40 non-null     float64
 24  (Performance académique,  score en première langue)                       40 non-null     float64
 25  (Informations sur l'école et le lieu de résidence, Public / Privé)        40 non-null     object
 26  (Informations sur l'école et le lieu de résidence, Zone)                  40 non-null     object
 27  (Informations sur l'école et le lieu de résidence, Nombre d'enseignants)  40 non-null     int64
 28  (Informations sur l'école et le lieu de résidence, Electricité)           40 non-null     object
 29  (Informations sur l'école et le lieu de résidence, Eau)                   40 non-null     object
 30  (Informations sur l'école et le lieu de résidence, pc)                    40 non-null     object
 31  (Informations sur l'école et le lieu de résidence, Livres)                40 non-null     object
 32  (Informations démographiques, État civil)                                 40 non-null     object
 33  (Informations démographiques, Origine)                                    0 non-null      float64
 34  (Informations psychologiques, motivation)                                 40 non-null     object
 35  (Informations psychologiques, Style d'apprentissage)                      40 non-null     object
 36  (Informations psychologiques, Satisfaction du cours)                      0 non-null      float64
 37  (انقطع | مثعثر دراسيا|جيد|, انقطع | مثعثر دراسيا|جيد|)                    40 non-null     object
dtypes: datetime64[ns](1), float64(10), int64(3), object(24)
memory usage: 12.0+ KB

In [ ]:
# Create a dictionary to store the sub-column information for each main column
sub_column_info = {}

# Iterate through the columns
for column in df.columns:
    # Check if the column is a tuple (MultiIndex)
    if isinstance(column, tuple):
        # The first part of the tuple is the main column name
        main_column = column[0]
        # The second part is the sub-column name
        sub_column = column[1]
    else:
        # If it's not a tuple, consider it as the main column name
        main_column = column
        sub_column = None

    # If the main column is not in the sub_column_info dictionary, initialize it
    if main_column not in sub_column_info:
        sub_column_info[main_column] = {"Sub-Columns": []}

    # Append the sub-column name to the list (None if it's not a MultiIndex)
    if sub_column is not None:
        sub_column_info[main_column]["Sub-Columns"].append(sub_column)

# Print the main column, sub-columns, and sub-column count
for main_column, info in sub_column_info.items():
    sub_columns = info["Sub-Columns"]
    sub_column_count = len(sub_columns)
    print(f"Main Column: {main_column}")
    print(f"Sub-Columns: {', '.join(sub_columns)}")
    print(f"Sub-Column Count: {sub_column_count}")
    print("\n")

Main Column: Unnamed: 0_level_0
Sub-Columns: code
Sub-Column Count: 1


Main Column: Informations personnelles
Sub-Columns: Age, Sexe, indigène, problèmes de santé, le travail à la maison, préscolaire, Travail, interne / externe
Sub-Column Count: 8


Main Column: Information familiale
Sub-Columns: Qualification de la mère,  Qualification Du père, Profession de la mère, Profession du père, Divorcé, Mort, Revenu familial, aide aux devoirs
Sub-Column Count: 8


Main Column: Performance académique
Sub-Columns: Specialté, Nombre de répitition, Score primaire, Score collégial, Score actuel, score en mathématiques,  score en langue arabe,  score en première langue
Sub-Column Count: 8


Main Column: Informations sur l'école et le lieu de résidence
Sub-Columns: Public / Privé, Zone, Nombre d'enseignants, Electricité, Eau, pc, Livres
Sub-Column Count: 7


Main Column: Informations démographiques
Sub-Columns: État civil, Origine
Sub-Column Count: 2


Main Column: Informations psychologiques
Sub-Columns: motivation, Style d'apprentissage, Satisfaction du cours
Sub-Column Count: 3


Main Column: انقطع | مثعثر دراسيا|جيد|
Sub-Columns: انقطع | مثعثر دراسيا|جيد|
Sub-Column Count: 1

In [ ]:
df.describe()

      Unnamed: 0_level_0 Informations personnelles Information familiale  \
                    code                  indigène       Revenu familial
count          40.000000                       0.0                   0.0
mean           20.500000                       NaN                   NaN
std            11.690452                       NaN                   NaN
min             1.000000                       NaN                   NaN
25%            10.750000                       NaN                   NaN
50%            20.500000                       NaN                   NaN
75%            30.250000                       NaN                   NaN
max            40.000000                       NaN                   NaN

      Performance académique                                              \
        Nombre de répitition Score primaire Score collégial Score actuel
count              40.000000      40.000000       40.000000    40.000000
mean                0.725000       6.575250        8.691750     7.897750
std                 0.784056       0.932941        1.972265     3.182061
min                 0.000000       5.220000        2.710000     0.000000
25%                 0.000000       5.875000        8.160000     7.320000
50%                 1.000000       6.455000        8.825000     8.790000
75%                 1.000000       7.092500        9.587500     9.522500
max                 3.000000       9.410000       16.410000    16.410000

                                                                               \
      score en mathématiques  score en langue arabe  score en première langue
count              40.000000              40.000000                 40.000000
mean                7.360750               8.118750                  7.877750
std                 3.610733               3.417905                  3.635874
min                 0.000000               0.000000                  0.000000
25%                 6.247500               7.390000                  5.850000
50%                 7.915000               9.125000                  8.850000
75%                 9.372500              10.030000                 10.212500
max                17.000000              16.000000                 15.340000

      Informations sur l'école et le lieu de résidence  \
                                  Nombre d'enseignants
count                                             40.0
mean                                              21.0
std                                                0.0
min                                               21.0
25%                                               21.0
50%                                               21.0
75%                                               21.0
max                                               21.0

      Informations démographiques Informations psychologiques
                          Origine       Satisfaction du cours
count                         0.0                         0.0
mean                          NaN                         NaN
std                           NaN                         NaN
min                           NaN                         NaN
25%                           NaN                         NaN
50%                           NaN                         NaN
75%                           NaN                         NaN
max                           NaN                         NaN

The columns containing NaN values and its count is 0, indicates that the column has no valid numerical data, and it's essentially an empty column with no numeric content.

Let's extract the NaN columns :

In [ ]:
# Determine which columns have all NaN values
nan_columns = [col for col in df.columns if df[col].isna().all()]

nan_columns

[('Informations personnelles', 'indigène'),
 ('Information familiale', 'Revenu familial'),
 ('Informations démographiques', 'Origine'),
 ('Informations psychologiques', 'Satisfaction du cours')]

Drop the NaN columns :

In [ ]:
df.drop(columns=nan_columns, inplace=True)

Verification :

In [ ]:
df.describe()

      Unnamed: 0_level_0 Performance académique                 \
                    code   Nombre de répitition Score primaire
count          40.000000              40.000000      40.000000
mean           20.500000               0.725000       6.575250
std            11.690452               0.784056       0.932941
min             1.000000               0.000000       5.220000
25%            10.750000               0.000000       5.875000
50%            20.500000               1.000000       6.455000
75%            30.250000               1.000000       7.092500
max            40.000000               3.000000       9.410000

                                                           \
      Score collégial Score actuel score en mathématiques
count       40.000000    40.000000              40.000000
mean         8.691750     7.897750               7.360750
std          1.972265     3.182061               3.610733
min          2.710000     0.000000               0.000000
25%          8.160000     7.320000               6.247500
50%          8.825000     8.790000               7.915000
75%          9.587500     9.522500               9.372500
max         16.410000    16.410000              17.000000

                                                        \
       score en langue arabe  score en première langue
count              40.000000                 40.000000
mean                8.118750                  7.877750
std                 3.417905                  3.635874
min                 0.000000                  0.000000
25%                 7.390000                  5.850000
50%                 9.125000                  8.850000
75%                10.030000                 10.212500
max                16.000000                 15.340000

      Informations sur l'école et le lieu de résidence
                                  Nombre d'enseignants
count                                             40.0
mean                                              21.0
std                                                0.0
min                                               21.0
25%                                               21.0
50%                                               21.0
75%                                               21.0
max                                               21.0

Check for missing values in all columns

In [ ]:
missing_values = df.isnull().sum()

# Print the count of missing values in each column
print("Missing Values in Each Column:")
print(missing_values)

Missing Values in Each Column:
Unnamed: 0_level_0                                code                         0
Informations personnelles                         Age                          0
                                                  Sexe                         0
                                                  problèmes de santé           0
                                                  le travail à la maison       0
                                                  préscolaire                  0
                                                  Travail                      0
                                                  interne / externe            0
Information familiale                             Qualification de la mère     0
                                                   Qualification Du père       0
                                                  Profession de la mère        0
                                                  Profession du père           0
                                                  Divorcé                      1
                                                  Mort                         0
                                                  aide aux devoirs             0
Performance académique                            Specialté                    0
                                                  Nombre de répitition         0
                                                  Score primaire               0
                                                  Score collégial              0
                                                  Score actuel                 0
                                                  score en mathématiques       0
                                                   score en langue arabe       0
                                                   score en première langue    0
Informations sur l'école et le lieu de résidence  Public / Privé               0
                                                  Zone                         0
                                                  Nombre d'enseignants         0
                                                  Electricité                  0
                                                  Eau                          0
                                                  pc                           0
                                                  Livres                       0
Informations démographiques                       État civil                   0
Informations psychologiques                       motivation                   0
                                                  Style d'apprentissage        0
انقطع | مثعثر دراسيا|جيد|                         انقطع | مثعثر دراسيا|جيد|    0
dtype: int64

We have a missing value in the subcolumn **"Divorcé"**. Let's check what dtype is the subcolumn :

In [ ]:
data_type = df['Information familiale', 'Divorcé'].dtype
print(f"Data Type of 'Divorcé' subcolumn: {data_type}")

Data Type of 'Divorcé' subcolumn: object

Fill missing values with **"NaN"**

In [ ]:
df['Information familiale', 'Divorcé'].fillna('NaN', inplace=True)

Now we verify :

In [ ]:
missing_values = df.isnull().sum()

# Print the count of missing values in each column
print("Missing Values in Each Column:")
print(missing_values)

Missing Values in Each Column:
Unnamed: 0_level_0                                code                         0
Informations personnelles                         Age                          0
                                                  Sexe                         0
                                                  problèmes de santé           0
                                                  le travail à la maison       0
                                                  préscolaire                  0
                                                  Travail                      0
                                                  interne / externe            0
Information familiale                             Qualification de la mère     0
                                                   Qualification Du père       0
                                                  Profession de la mère        0
                                                  Profession du père           0
                                                  Divorcé                      0
                                                  Mort                         0
                                                  aide aux devoirs             0
Performance académique                            Specialté                    0
                                                  Nombre de répitition         0
                                                  Score primaire               0
                                                  Score collégial              0
                                                  Score actuel                 0
                                                  score en mathématiques       0
                                                   score en langue arabe       0
                                                   score en première langue    0
Informations sur l'école et le lieu de résidence  Public / Privé               0
                                                  Zone                         0
                                                  Nombre d'enseignants         0
                                                  Electricité                  0
                                                  Eau                          0
                                                  pc                           0
                                                  Livres                       0
Informations démographiques                       État civil                   0
Informations psychologiques                       motivation                   0
                                                  Style d'apprentissage        0
انقطع | مثعثر دراسيا|جيد|                         انقطع | مثعثر دراسيا|جيد|    0
dtype: int64

## **Data standardization**

In [ ]:
# Iterate through columns to show attributes
for column in df.columns:
    print(f"Column: {column}")

    # Get the subcolumn data within the column
    subcolumn_data = df[column]
    unique_values = subcolumn_data.unique()
    unique_count = subcolumn_data.nunique()
    data_type = subcolumn_data.dtypes

    print(f"  Unique Values: {unique_values}")
    print(f"  Number of Unique Values: {unique_count}")
    print(f"  Data Type: {data_type}\n")

Column: ('Unnamed: 0_level_0', 'code')
  Unique Values: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
  Number of Unique Values: 40
  Data Type: int64

Column: ('Informations personnelles', 'Age')
  Unique Values: ['2010-01-19T00:00:00.000000000' '2004-11-19T00:00:00.000000000'
 '2008-01-09T00:00:00.000000000' '2008-11-22T00:00:00.000000000'
 '2007-01-24T00:00:00.000000000' '2008-08-15T00:00:00.000000000'
 '2008-06-08T00:00:00.000000000' '2005-11-15T00:00:00.000000000'
 '2008-12-09T00:00:00.000000000' '2009-07-16T00:00:00.000000000'
 '2007-05-18T00:00:00.000000000' '2005-01-05T00:00:00.000000000'
 '2005-08-01T00:00:00.000000000' '2007-03-18T00:00:00.000000000'
 '2010-01-22T00:00:00.000000000' '2009-03-24T00:00:00.000000000'
 '2007-12-05T00:00:00.000000000' '2008-01-21T00:00:00.000000000'
 '2007-07-26T00:00:00.000000000' '2007-11-23T00:00:00.000000000'
 '2008-12-30T00:00:00.000000000' '2008-04-21T00:00:00.000000000'
 '2008-11-10T00:00:00.000000000' '2007-05-22T00:00:00.000000000'
 '2008-09-27T00:00:00.000000000' '2006-03-12T00:00:00.000000000'
 '2005-11-18T00:00:00.000000000' '2007-02-16T00:00:00.000000000'
 '2005-11-29T00:00:00.000000000' '2004-09-22T00:00:00.000000000'
 '2006-04-29T00:00:00.000000000' '2004-11-02T00:00:00.000000000'
 '2008-03-20T00:00:00.000000000' '2006-10-17T00:00:00.000000000'
 '2006-09-06T00:00:00.000000000' '2005-06-23T00:00:00.000000000'
 '2005-07-25T00:00:00.000000000' '2007-05-02T00:00:00.000000000'
 '2006-01-17T00:00:00.000000000']
  Number of Unique Values: 39
  Data Type: datetime64[ns]

Column: ('Informations personnelles', 'Sexe')
  Unique Values: ['F' 'M']
  Number of Unique Values: 2
  Data Type: object

Column: ('Informations personnelles', 'problèmes de santé')
  Unique Values: ['psychique' 'Non' 'Oui']
  Number of Unique Values: 3
  Data Type: object

Column: ('Informations personnelles', 'le travail à la maison')
  Unique Values: ['oui' 'non' 'Non' 'Oui']
  Number of Unique Values: 4
  Data Type: object

Column: ('Informations personnelles', 'préscolaire')
  Unique Values: ['non']
  Number of Unique Values: 1
  Data Type: object

Column: ('Informations personnelles', 'Travail')
  Unique Values: ['non']
  Number of Unique Values: 1
  Data Type: object

Column: ('Informations personnelles', 'interne / externe')
  Unique Values: ['interne ' 'externe' 'Interne' 'Externe' 'Extrene']
  Number of Unique Values: 5
  Data Type: object

Column: ('Information familiale', 'Qualification de la mère')
  Unique Values: ['non']
  Number of Unique Values: 1
  Data Type: object

Column: ('Information familiale', ' Qualification Du père')
  Unique Values: ['oui' 'Non']
  Number of Unique Values: 2
  Data Type: object

Column: ('Information familiale', 'Profession de la mère')
  Unique Values: ['sans profession']
  Number of Unique Values: 1
  Data Type: object

Column: ('Information familiale', 'Profession du père')
  Unique Values: ['Fqih' 'Agriculture' 'Commerce' 'décédé']
  Number of Unique Values: 4
  Data Type: object

Column: ('Information familiale', 'Divorcé')
  Unique Values: ['non' 'NaN']
  Number of Unique Values: 2
  Data Type: object

Column: ('Information familiale', 'Mort')
  Unique Values: ['non' 'Oui']
  Number of Unique Values: 2
  Data Type: object

Column: ('Information familiale', 'aide aux devoirs')
  Unique Values: ['non' 'oui' 'Non']
  Number of Unique Values: 3
  Data Type: object

Column: ('Performance académique', 'Specialté')
  Unique Values: ['collège']
  Number of Unique Values: 1
  Data Type: object

Column: ('Performance académique', 'Nombre de répitition')
  Unique Values: [0 2 1 3]
  Number of Unique Values: 4
  Data Type: int64

Column: ('Performance académique', 'Score primaire')
  Unique Values: [8.75 6.45 6.3  5.23 6.33 5.54 6.03 5.95 6.21 5.22 7.1  6.16 5.85 7.32
 5.86 6.46 6.41 7.53 6.43 8.05 6.75 6.57 7.09 8.03 7.27 7.21 5.56 6.63
 6.91 5.43 6.98 6.72 5.47 5.42 9.41 6.5  5.88 5.77]
  Number of Unique Values: 38
  Data Type: float64

Column: ('Performance académique', 'Score collégial')
  Unique Values: [16.41  4.75  8.8   2.71  8.19  6.65  6.5   6.31  7.02  7.9   6.42  9.14
  9.67  9.4   9.3   9.9   7.42  8.78  8.72  9.08  8.49  9.56  9.74  9.84
  9.33  8.7   8.69  9.72  9.51  9.96  8.07  8.56  9.05  8.85  9.41  9.87
  9.98]
  Number of Unique Values: 37
  Data Type: float64

Column: ('Performance académique', 'Score actuel')
  Unique Values: [16.41  4.75  0.    6.5   6.31  7.02  7.9   6.42  9.14  9.67  9.4   9.3
  9.9   7.42  8.78  8.72  9.08  8.49  9.56  9.74  9.84  9.33  8.7   8.69
  9.72  9.51  8.8   9.96  8.07  8.56  9.05  5.85  8.    9.87  8.98]
  Number of Unique Values: 35
  Data Type: float64

Column: ('Performance académique', 'score en mathématiques')
  Unique Values: [17.    5.    0.    5.33  6.83  3.67  8.67  6.33 10.67  9.33  7.    5.67
 11.67 11.    6.   11.33  9.5   8.33  9.75 10.83  8.    7.67  7.33  8.17
  7.83  6.67 10.  ]
  Number of Unique Values: 27
  Data Type: float64

Column: ('Performance académique', ' score en langue arabe')
  Unique Values: [16.    7.    0.    6.44  4.75  7.06  9.12  2.5   9.13  8.66  8.84  9.75
 10.41 10.   10.69  8.06  8.44  9.19 10.38 10.12  8.62 10.5   9.53 11.09
  7.5  10.44  7.53  9.81 10.88  9.5   7.69  8.25]
  Number of Unique Values: 32
  Data Type: float64

Column: ('Performance académique', ' score en première langue')
  Unique Values: [15.34  6.    0.    7.3   4.72  4.1   5.7   2.6   8.7   9.6   8.9   7.95
  5.1  11.4   5.9  10.25  9.7   9.2  10.1  11.2  11.8   9.3   5.   10.2
 10.6   8.3   7.9  11.3   7.25  8.8   8.  ]
  Number of Unique Values: 31
  Data Type: float64

Column: ("Informations sur l'école et le lieu de résidence", 'Public / Privé')
  Unique Values: ['Public' 'public']
  Number of Unique Values: 2
  Data Type: object

Column: ("Informations sur l'école et le lieu de résidence", 'Zone')
  Unique Values: ['rurale']
  Number of Unique Values: 1
  Data Type: object

Column: ("Informations sur l'école et le lieu de résidence", "Nombre d'enseignants")
  Unique Values: [21]
  Number of Unique Values: 1
  Data Type: int64

Column: ("Informations sur l'école et le lieu de résidence", 'Electricité')
  Unique Values: ['oui']
  Number of Unique Values: 1
  Data Type: object

Column: ("Informations sur l'école et le lieu de résidence", 'Eau')
  Unique Values: ['oui']
  Number of Unique Values: 1
  Data Type: object

Column: ("Informations sur l'école et le lieu de résidence", 'pc')
  Unique Values: ['non']
  Number of Unique Values: 1
  Data Type: object

Column: ("Informations sur l'école et le lieu de résidence", 'Livres')
  Unique Values: ['oui']
  Number of Unique Values: 1
  Data Type: object

Column: ('Informations démographiques', 'État civil')
  Unique Values: ['célibataire']
  Number of Unique Values: 1
  Data Type: object

Column: ('Informations psychologiques', 'motivation')
  Unique Values: ['oui' 'Non' 'Oui']
  Number of Unique Values: 3
  Data Type: object

Column: ('Informations psychologiques', "Style d'apprentissage")
  Unique Values: ['Normal']
  Number of Unique Values: 1
  Data Type: object

Column: ('انقطع | مثعثر دراسيا|جيد|', 'انقطع | مثعثر دراسيا|جيد|')
  Unique Values: ['انقطعت' 'انقطع' 'متعثر']
  Number of Unique Values: 3
  Data Type: object

I noticed that some columns needs to be standardize :

1. **"le travail à la maison"** has 4 unique values : 'oui', 'Oui', 'non' and 'Non'. We should edit our code in order to have 'oui' and 'non'.

2. **"interne/externe"** has 5 unique values : 'interne', 'Interne', 'externe', 'Externe' and 'Extrene'. We should have 'interne' and 'externe'.

3. **"aide aux devoirs"** has 3 unique values : 'oui', 'non' and 'Non'. We should edit our code in order to have 'interne' and 'externe'.

4. **"Public / Privé"** has 2 unique values : 'Public' and 'public'. We should have only 'public'.

5. **"motivation"** has 3 unique values : 'oui', 'Oui' and 'Non'.  We should edit our code in order to have 'oui' and 'non'.

List of columns and subcolumns to standardize :

In [ ]:
columns_to_standardize = [
    ('Informations personnelles', 'le travail à la maison'),
    ('Informations personnelles', 'interne / externe'),
    ('Information familiale', 'aide aux devoirs'),
    ("Informations sur l'école et le lieu de résidence", 'Public / Privé'),
    ('Informations psychologiques', 'motivation'),
]

Function to standardize text values to lowercase

In [ ]:
def standardize_to_lowercase(column):
    df[column] = df[column].str.lower()

Apply standardization to the list of columns

In [ ]:
for column in columns_to_standardize:
    standardize_to_lowercase(column)

New let's check if the problem is solved or not :

In [ ]:
# List of columns and subcolumns to check after standardization
columns_to_check = [
    ('Informations personnelles', 'le travail à la maison'),
    ('Informations personnelles', 'interne / externe'),
    ('Information familiale', 'aide aux devoirs'),
    ("Informations sur l'école et le lieu de résidence", 'Public / Privé'),
    ('Informations psychologiques', 'motivation'),
]

# Check and display unique values in the specified columns
for column in columns_to_check:
    unique_values = df[column].unique()
    print(f"Unique values in '{column}': {unique_values}")

Unique values in '('Informations personnelles', 'le travail à la maison')': ['oui' 'non']
Unique values in '('Informations personnelles', 'interne / externe')': ['interne ' 'externe' 'interne' 'extrene']
Unique values in '('Information familiale', 'aide aux devoirs')': ['non' 'oui']
Unique values in '("Informations sur l'école et le lieu de résidence", 'Public / Privé')': ['public']
Unique values in '('Informations psychologiques', 'motivation')': ['oui' 'non']

As we can see, the subcolumn 'interne / externe' has 4 unique values we should edit it :

In [ ]:
# Function to standardize text values in the 'interne / externe' subcolumn
def standardize_interne_externe(main_column, sub_column):
    mapping = {
        'interne': 'interne',
        'externe': 'externe',
        'interne ': 'interne',
        'extrene': 'externe',
    }

    df[(main_column, sub_column)] = df[(main_column, sub_column)].map(mapping)

# Apply standardization to the 'interne / externe' subcolumn
standardize_interne_externe('Informations personnelles', 'interne / externe')

# Check and display unique values in the 'interne / externe' subcolumn
unique_values = df[('Informations personnelles', 'interne / externe')].unique()
print(f"Unique values in 'interne / externe': {unique_values}")

Unique values in 'interne / externe': ['interne' 'externe']

Also the column **"Age"** contains borth dates not ages so let's change this by converting the column into datetime format and substract it from  the current date :

In [ ]:
df[("Informations personnelles", "Age")] = pd.to_datetime(df[("Informations personnelles", "Age")], format="%d/%m/%Y")

# The current date
current_date = datetime.now()

# Calculate the age by subtracting the birthdate from the current date
df[("Informations personnelles", "Age")] = (current_date - df[("Informations personnelles", "Age")]).dt.days // 365

  Verification :

In [ ]:
df[("Informations personnelles", "Age")]

0     13
1     18
2     15
3     14
4     16
5     15
6     15
7     17
8     14
9     14
10    16
11    18
12    18
13    16
14    13
15    14
16    15
17    15
18    16
19    15
20    14
21    15
22    14
23    16
24    15
25    17
26    17
27    16
28    17
29    19
30    17
31    19
32    16
33    15
34    17
35    17
36    18
37    18
38    16
39    17
Name: (Informations personnelles, Age), dtype: int64

## **Export data**

In [ ]:
output_file = "base de données clean.xlsx"
df.to_excel(output_file)

In [ ]:
# Load the XLSX file
file_path = "base de données clean.xlsx"
df = pd.read_excel(file_path, header=[0, 1])

# Flatten the MultiIndex columns
df.columns = ['_'.join(col).strip() if col[1] else col[0] for col in df.columns]

# Save as CSV
output_csv = "base_de_donnees_clean.csv"
df.to_csv(output_csv)

In [ ]:
file_path = "base_de_donnees_clean.csv"
dfff = pd.read_csv(file_path)

# List all columns and their subcolumns
for column in dfff.columns:
    # Split the column name using underscores to separate main column and subcolumn
    parts = column.split('_')

    if len(parts) == 1:
        # Main column without subcolumn
        main_column = parts[0]
        subcolumn = None
    else:
        # Main column with subcolumn
        main_column = parts[0]
        subcolumn = parts[1]

    print("Main Column:", main_column)
    print("Subcolumn:", subcolumn)
    print("\n")

Main Column: Unnamed: 0
Subcolumn: None


Main Column: Unnamed: 0
Subcolumn: level


Main Column: Unnamed: 0
Subcolumn: level


Main Column: Informations personnelles
Subcolumn: Age


Main Column: Informations personnelles
Subcolumn: Sexe


Main Column: Informations personnelles
Subcolumn: problèmes de santé


Main Column: Informations personnelles
Subcolumn: le travail à la maison


Main Column: Informations personnelles
Subcolumn: préscolaire


Main Column: Informations personnelles
Subcolumn: Travail


Main Column: Informations personnelles
Subcolumn: interne / externe


Main Column: Information familiale
Subcolumn: Qualification de la mère


Main Column: Information familiale
Subcolumn:  Qualification Du père


Main Column: Information familiale
Subcolumn: Profession de la mère


Main Column: Information familiale
Subcolumn: Profession du père


Main Column: Information familiale
Subcolumn: Divorcé


Main Column: Information familiale
Subcolumn: Mort


Main Column: Information familiale
Subcolumn: aide aux devoirs


Main Column: Performance académique
Subcolumn: Specialté


Main Column: Performance académique
Subcolumn: Nombre de répitition


Main Column: Performance académique
Subcolumn: Score primaire


Main Column: Performance académique
Subcolumn: Score collégial


Main Column: Performance académique
Subcolumn: Score actuel


Main Column: Performance académique
Subcolumn: score en mathématiques


Main Column: Performance académique
Subcolumn:  score en langue arabe


Main Column: Performance académique
Subcolumn:  score en première langue


Main Column: Informations sur l'école et le lieu de résidence
Subcolumn: Public / Privé


Main Column: Informations sur l'école et le lieu de résidence
Subcolumn: Zone


Main Column: Informations sur l'école et le lieu de résidence
Subcolumn: Nombre d'enseignants


Main Column: Informations sur l'école et le lieu de résidence
Subcolumn: Electricité


Main Column: Informations sur l'école et le lieu de résidence
Subcolumn: Eau


Main Column: Informations sur l'école et le lieu de résidence
Subcolumn: pc


Main Column: Informations sur l'école et le lieu de résidence
Subcolumn: Livres


Main Column: Informations démographiques
Subcolumn: État civil


Main Column: Informations psychologiques
Subcolumn: motivation


Main Column: Informations psychologiques
Subcolumn: Style d'apprentissage


Main Column: انقطع | مثعثر دراسيا|جيد|
Subcolumn: انقطع | مثعثر دراسيا|جيد|

# **Data Visualization Design with choice justification :**

I decided to use different data viz.

## **Bar chart for the times students failed the class**

![barchart.png]()

* Green to represent students who didn't fail any classes. This color suggests success and achievement.
* Yellow for students who failed one class. This color can represent a warning or a minor setback.
* Orange to indicate students who failed two classes. This color can signify a more significant issue but still not a complete failure.
* Red for students who failed three classes, a dark red or burgundy color can be used. This color signifies a critical situation or a high level of failure.

## **Pie chart to visualize : انقطع | مثعثر دراسيا|جيد|**

![piechart.png]()

* انقطع (Discontinued): Light shade of red to mention that we need to pay attention to boys dropping out.

* مثعثر دراسيا (Academically Scattered): Orange in order to pay attention it could turn into a red because a scattered student can drop out.

* انقطعت (Dropped Out): A darker shade of red because it signifies : girls are dropping out and as we know in rural areas it's a big a problem.

## **Scatter plot**

![image.png]()

We need to see the age of our 40 students:
* Green for students from 12 to 15 because it's the normal age of students in middle school.
* Orange for students from 16 to 17 because we need to help them because they may have problems of .
* Red for students from 18 to 19 because these students can be expulsed from middle school.

## **Graphic curve for performance by subject**

![image.png]()

* Math in blue: Blue is often associated with logic and knowledge, making it a suitable choice for a math curve.

* Arabic in green: Green can symbolize growth and learning, which is appropriate for language subjects.

* Mother Language in orange: Warm colors can evoke emotions and represent familiarity, which can be relevant to one's mother language.